[palette]
bg0 = "#ffffff" # 0
bg1 = "#f4f4f4" # -11
bg2 = "#ebebeb" # -9
bg3 = "#e4e4e4" # -7
bg4 = "#dfdfdf" # -5
bg5 = "#dcdcdc" # -3
fg0 = "#333333"
fg1 = "#202020"
fg2 = "#000000"
fg3 = "#777777"

bg_cursor = "#fafafa"

# TODO: make brighter variants of these (e.g. for terminal brights)
red    = "#904961" # oklch(50% 0.1 0)
orange = "#934c3d" # oklch(50% 0.1 33)
yellow = "#b5803e" # oklch(64% 0.105 70)
green  = "#427138" # oklch(50% 0.1 140)
aqua   = "#117555" # oklch(50% 0.1 165)
blue   = "#535d9c" # oklch(50% 0.1 275)
purple = "#79508a" # oklch(50% 0.1 315)

bg_red    = "#e9dbdf" # 20% opacity red over bg0
bg_orange = "#e9dbd8" # 20% opacity orange over bg0
bg_yellow = "#f0e6d8" # ditto
bg_green  = "#d9e3d7" # etc
bg_aqua   = "#cfe3dd"
bg_blue   = "#dddfeb"
bg_purple = "#e4dce8"
